# -*- coding: utf-8 -*-
"""GenAI_final_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6fc_1LISQ9wHUktWxT4QYVIXaA-OFv7

Product link: https://www.amazon.com/Hario-V60-Ceramic-Dripper-Filters/dp/B01L6OCXAS/ref=sr_1_1?crid=2SOQY70VSQIG3&dib=eyJ2IjoiMSJ9.eSM6LPZ4S5wipqlclhxNTDyZa1uuAEcX3nIjIi8L9LNhI0veYm2qpvVXMqMQGJiH62b4qR5k3_YXDmbD2_tX65mrcK_uDvk7neNkokD7aeKpzhatEkoX1H9i9-kx7T5zul4rZCWc4Iv-XFdfS6AuA0t1vhIJ1pDo4-Ne8ZhmEOFye5MSHgEQZ0ss0j6V9gWJU7XNc3XswY0olmB586YWSpGMR25KD7jV6wO81NVm8UI0sBT_GedT9alcdOCgeCq-HEGNJ4imzIxLMDJytYoGDeAOXXBi_SmZVX8DH0gEK6w.-nXutUkCUzm2bgscyfiVReU281IUNdTCvSfLahMTjQE&dib_tag=se&keywords=HARIO%2BV60%2BPour-Over%2BCoffee%2BDripper%2B%26%2BServer%2BSet&nsdOptOutParam=true&qid=1764454090&sprefix=hario%2Bv60%2Bpour-over%2Bcoffee%2Bdripper%2B%26%2Bserver%2Bset%2Caps%2C132&sr=8-1&th=1

## Reason for selecting this product
1. Rich and Distinct Visual Features (Great for Diffusion Models)
2. Large Volume of Detailed Customer Reviews
3. Highly Effective for Prompt Engineering
4. Strong Real Product Images for Comparison

## Product Description
The Hario Pour over Coffee starter set is the perfect setup as a gift or a gift for yourself. Start your journey into great Coffee. You'll look forward to waking up every single day! If you're looking to get started with Coffee brewing, or know someone you'd like to get started with manual brewing (and has a birthday coming up), then this Hario Starter kit was made for you. This great value boxed kit comes with a Hario V60 Coffee dripper, a Hario V60 Coffee server, a coffee scoop and a 100-Pack of V60 Filters.

## Reviews
1. I had read that pour over drip coffee is the healthiest brewing method as it filters out the oils that can cause higher LDL cholesterol levels. I chose this kit as it was priced well and included the filters. Durability was as issue for some but I found the ceramic dripper to be thick and sturdy. Works well for my husband and I. And the coffee taste is EXCELLENT! I use a strong roast, course grind, which I grind at the grocery store. It’s new for me so I will yet experiment with drip grind and medium roast. I’m also going to experiment with metal funnel as well as the paper ones.
2. I just started learning how to do. Pour overs. Definitely a game changer for a smoother enjoyable cup of coffee! This is a great starter kit, which has everything you need. And is a very good product that I will be using for years to come!
3. So far its been great! Heavy construction, and the carafe is a great size. I'm just learning to nuances of pour over coffee, but this was an excellent place to start. I chose it based on other reviews, and I'm glad I did.
4. I really like the filters and carafe. Cheaper filters clog and don't let the coffee flow, making it burst or over-brew. These filters are not cheap and allow for great flow rate. The carafe (glass server) is very useful for making more than 1 cup (e.g. Making 2 8oz cups for 2 people)
Be aware that this is a good setup for brewing 600ml / 18fl oz and not much more. If you want 4 8pz cups, get a bigger size
5. I can't explain how much I love this. Coming from a Nespresso machine to this, and I am so much happier. The taste, and simplicity are top notch. Plus the act of brewing with this is very peaceful. Highly recommend.
"""

description = """
The Hario Pour over Coffee starter set is the perfect setup as a gift or a gift for yourself. Start your journey into great Coffee. You'll look forward to waking up every single day! If you're looking to get started with Coffee brewing, or know someone you'd like to get started with manual brewing (and has a birthday coming up), then this Hario Starter kit was made for you. This great value boxed kit comes with a Hario V60 Coffee dripper, a Hario V60 Coffee server, a coffee scoop and a 100-Pack of V60 Filters.
"""
reviews=[
    '''
    I had read that pour over drip coffee is the healthiest brewing method as it filters out the oils that can cause higher LDL cholesterol levels. I chose this kit as it was priced well and included the filters. Durability was as issue for some but I found the ceramic dripper to be thick and sturdy. Works well for my husband and I. And the coffee taste is EXCELLENT! I use a strong roast, course grind, which I grind at the grocery store. It’s new for me so I will yet experiment with drip grind and medium roast. I’m also going to experiment with metal funnel as well as the paper ones.
    ''',
    '''
    I just started learning how to do. Pour overs. Definitely a game changer for a smoother enjoyable cup of coffee! This is a great starter kit, which has everything you need. And is a very good product that I will be using for years to come!
    ''',
    '''
    So far its been great! Heavy construction, and the carafe is a great size. I'm just learning to nuances of pour over coffee, but this was an excellent place to start. I chose it based on other reviews, and I'm glad I did.
    ''',
    '''
    I really like the filters and carafe. Cheaper filters clog and don't let the coffee flow, making it burst or over-brew. These filters are not cheap and allow for great flow rate. The carafe (glass server) is very useful for making more than 1 cup (e.g. Making 2 8oz cups for 2 people) Be aware that this is a good setup for brewing 600ml / 18fl oz and not much more. If you want 4 8pz cups, get a bigger size
    ''',
    '''
    I can't explain how much I love this. Coming from a Nespresso machine to this, and I am so much happier. The taste, and simplicity are top notch. Plus the act of brewing with this is very peaceful. Highly recommend.
    '''
]
corpus_text = "PRODUCT DESCRIPTION:\n" + description + "\n\nCUSTOMER REVIEWS:\n" + "\n\n".join(reviews)

from openai import OpenAI
client = OpenAI()

# -----------------------------
# Utility: Chat Completion Call
# -----------------------------
def ask_gpt(prompt, model="gpt-5.1"):
    response = client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
    )
    return response.choices[0].message.content


# -----------------------------
# Prompt Templates for Q2
# -----------------------------
def build_summarization_prompt(text):
    return f"""
You are an expert product analyst.

Summarize the following product reviews into a concise and comprehensive overview.
Focus on key themes, user experiences, pros, cons, and recurring patterns.

Return the output in the following structure:
- Overall Summary
- Top Positive Points
- Top Negative Points
- Frequently Mentioned Keywords

Reviews:
{text}
"""


def build_visual_feature_prompt(text):
    return f"""
You are an expert in extracting visual and physical product characteristics from text.

From the following product reviews, extract ONLY concrete visual or physical features of the product.
Include attributes such as: shape, color, material, texture, size, special patterns, and usage environment.

Return the output in JSON with this structure:
{{
  "materials": [],
  "colors": [],
  "shapes": [],
  "textures": [],
  "distinctive_patterns": [],
  "functional_visual_elements": [],
  "common_usage_scenes": []
}}

Reviews:
{text}
"""


def build_sentiment_prompt(text):
    return f"""
You are an expert sentiment analyst.

Analyze the sentiment of the following product reviews.
Provide:
1. Overall sentiment (Positive / Neutral / Negative)
2. Sentiment distribution (%)
3. Top 5 reasons for positive sentiment
4. Top 5 reasons for negative sentiment
5. One-sentence emotional summary

Reviews:
{text}
"""


def build_topic_extraction_prompt(text):
    return f"""
You are a topic modeling expert.

Identify the major topics discussed in these product reviews.
Cluster the reviews into 3–6 coherent topics and describe each topic briefly.

Return the output in this format:
Topic Name:
- Description:
- Representative Keywords:
- Representative User Comments (short phrases):

Reviews:
{text}
"""


# -----------------------------
# Functions to Run All Prompts
# -----------------------------
def run_summarization(text):
    prompt = build_summarization_prompt(text)
    return ask_gpt(prompt)


def run_visual_feature_extraction(text):
    prompt = build_visual_feature_prompt(text)
    return ask_gpt(prompt)


def run_sentiment_analysis(text):
    prompt = build_sentiment_prompt(text)
    return ask_gpt(prompt)


def run_topic_extraction(text):
    prompt = build_topic_extraction_prompt(text)
    return ask_gpt(prompt)

# Example: Insert chunked (or single) review text
sample_reviews = """
The glass of the Hario V60 server is beautifully clear and feels durable.
The spiral ribs on the dripper really help the water flow evenly.
I love the wooden handle—very elegant. Coffee flavor improved a lot!
A bit fragile, so handle carefully. But visually it's stunning.
"""
print("=== Summarization ===")
print(run_summarization(sample_reviews))
print("\n=== Visual Feature Extraction ===")
print(run_visual_feature_extraction(sample_reviews))
print("\n=== Sentiment Analysis ===")
print(run_sentiment_analysis(sample_reviews))
print("\n=== Topic Extraction ===")
print(run_topic_extraction(sample_reviews))

# === Q2: Summarization ===
summary_result = run_summarization(corpus_text)
print("===== SUMMARIZATION =====")
print(summary_result)

# === Q2: Visual Feature Extraction ===
visual_features_result = run_visual_feature_extraction(corpus_text)
print("\n===== VISUAL FEATURES (JSON) =====")
print(visual_features_result)

# === Q2: Sentiment Analysis ===
sentiment_result = run_sentiment_analysis(corpus_text)
print("\n===== SENTIMENT ANALYSIS =====")
print(sentiment_result)

# === (Optional) Topic Extraction ===
topics_result = run_topic_extraction(corpus_text)
print("\n===== TOPIC EXTRACTION =====")
print(topics_result)

analysis_output = {
    "summary": summary_result,
    "visual_features": visual_features_result,
    "sentiment": sentiment_result,
    "topics": topics_result,
}

prompts = [
    # Prompt 1
    "A clean, high-resolution product photo of a Hario-style V60 pour-over starter kit on a white seamless background. The kit includes a thick, sturdy white ceramic cone dripper with V60 spiral ribs, a clear glass server marked up to about 600 ml (18 fl oz), a bag of white paper filters (100-pack), and a simple coffee scoop. Emphasize the smooth ceramic texture, the transparency and reflections on the glass server, and the minimal, modern Japanese aesthetic. Soft diffused lighting, sharp focus, no clutter.",

    # Prompt 2
    "A cozy early-morning kitchen scene showing someone slowly pouring hot water from a gooseneck kettle into a white ceramic V60 dripper with spiral ribs placed on top of a clear 600-ml glass server. Steam rises gently as coffee drips through a paper filter with smooth, even flow. Two 8-oz mugs wait nearby. The mood is calm, peaceful, and ritualistic, highlighting the enjoyable, meditative brewing experience praised by reviewers.",

    # Prompt 3
    "A close-up macro shot of the V60 dripper showing a white paper filter with medium-coarse grounds and clear water flowing smoothly through without clogging. The spiral ribs of the ceramic cone are visible. Coffee drips in a steady stream into the transparent glass server below. Highlight clarity, smooth flow rate, and the high-quality filter performance mentioned by users.",

    # Prompt 4
    "A top-down flat-lay image showing all components of a pour-over coffee starter kit arranged neatly: a white ceramic V60 dripper, a clear glass coffee server with 600-ml markings, a stack of white V60 paper filters (100-pack), and a small coffee scoop. Bright, minimal, modern composition with soft shadows.",

    # Prompt 5
    "A split-scene comparison between a manual pour-over coffee setup and a capsule coffee machine. The pour-over side shows a white ceramic V60 dripper on a clear 600-ml glass server filled with freshly brewed coffee; the machine side shows a Nespresso-style device. The pour-over side should look smoother, healthier, and more natural, reflecting reviewers' opinions.",

    # Prompt 6
    "A realistic product photo showing a white ceramic V60 dripper brewing into a clear 600-ml glass server. The server is filled to about 18 fl oz (enough for two 8-oz cups). Minimalist, modern kitchen in the background, highlighting small-batch brewing for one or two people."
]

import base64
from openai import OpenAI
from diffusers import StableDiffusionPipeline
import torch

# ========================
# 1. OpenAI Model
# ========================

def generate_images_openai(prompts):
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    os.makedirs("images_openai", exist_ok=True)

    for i, prompt in enumerate(prompts):
        response = client.images.generate(
            model="gpt-image-1",
            prompt=prompt,
            n=1,
            size="1024x1024"
        )
        image_b64 = response.data[0].b64_json
        image_bytes = base64.b64decode(image_b64)

        filename = f"images_openai/v60_openai_{i+1}.png"
        with open(filename, "wb") as f:
            f.write(image_bytes)

        print(f"[OpenAI] Saved: {filename}")


# ========================
# 2. Stable Diffusion Model
# ========================

def load_sd():
    model_id = "runwayml/stable-diffusion-v1-5"
    pipe = StableDiffusionPipeline.from_pretrained(
        model_id,
        torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
    )
    if torch.cuda.is_available():
        pipe = pipe.to("cuda")
    return pipe

def generate_images_sd(prompts, pipe):
    os.makedirs("images_sd", exist_ok=True)

    for i, prompt in enumerate(prompts):
        img = pipe(prompt).images[0]
        filename = f"images_sd/v60_sd_{i+1}.png"
        img.save(filename)
        print(f"[StableDiffusion] Saved: {filename}")

# ========================
# Run Both Models
# ========================
print("Generating images with Stable Diffusion...")
sd_pipe = load_sd()
generate_images_sd(prompts, sd_pipe)

